.gitignore, oxd-gen-client/src/main/java/io/swagger/client/model/GetClientTokenResponseData.java, oxd-gen-client/src/main/java/io/swagger/client/model/RegisterSiteParams.java, oxd-gen-client/src/test/java/io/swagger/client/api/RemoveSiteTest.java
@yuriyz . Will you please review ?
=> Swagger Test - Scope Array Fix

oxd-gen-client/src/main/java/io/swagger/client/model/GetUserInfoResponse.java, oxd-gen-client/src/test/java/io/swagger/client/api/GetTokensByCodeTest.java, oxd-gen-client/src/test/java/io/swagger/client/api/GetUserInfoTest.java, oxd-server/src/main/resources/swagger.yaml, oxd-server/src/test/resources/testng.xml
Added test for user info API ?
=> Swagger test for User Info API

oxd-gen-client/src/main/java/io/swagger/client/model/GetLogoutUriResponse.java, oxd-gen-client/src/test/java/io/swagger/client/api/GetLogoutUrlTest.java, oxd-server/src/main/resources/swagger.yaml, oxd-server/src/test/resources/testng.xml
Tests for verifying logout URI endpoint.
=> Logout Url endpoint swagger test 

oxd-common/src/main/java/org/xdi/oxd/common/ErrorResponseCode.java
Change String for invalid Oxd_id error
=> Change String for invalid Oxd_id error

oxd-server/src/test/java/org/xdi/oxd/server/HealthCheckTest.java, oxd-server/src/test/resources/testng.xml
/healthcheck response should be JSON #267
=> /healthcheck response should be JSON #267

oxd-server/src/main/java/org/xdi/oxd/server/RestResource.java, oxd-server/src/test/java/org/xdi/oxd/server/HealthCheckTest.java
health Test Failed at jenkin fix , while there are two more test failed at introspect access token that might be due to wrong config file.
=> health Test Failed at jenkin fix

oxd-common/src/main/java/org/xdi/oxd/common/response/RegisterSiteResponse.java, oxd-gen-client/src/main/java/io/swagger/client/model/RegisterSiteResponse.java, oxd-server/src/main/java/org/xdi/oxd/server/op/RegisterSiteOperation.java, oxd-server/src/main/resources/swagger.yaml
Return client_name in register_site response
=> Return client_name in register_site response

oxd-gen-client/src/test/java/io/swagger/client/api/UmaFullTest.java, oxd-server/src/main/java/org/gluu/oxd/server/op/RpGetRptOperation.java
#323 - Fix and enable back two tests which are failing against ce-dev5
https://github.com/GluuFederation/oxd/issues/323
=> Issue#323 - Fix and enable back two tests which are failing against ce-dev5

oxd-common/src/main/java/org/gluu/oxd/common/ErrorResponseCode.java, oxd-server/src/main/java/org/gluu/oxd/server/service/DiscoveryService.java
Issue#272 - Improve log message if certificate is not imported
https://github.com/GluuFederation/oxd/issues/272
=> Issue#272 - Improve log message if certificate is not imported

oxd-server/src/main/java/org/gluu/oxd/server/Cli.java, oxd-server/src/main/java/org/gluu/oxd/server/service/ValidationService.java
Issue#329 - oxd: Getting Forbidden : 403 while using lsox script
https://github.com/GluuFederation/oxd/issues/329
**Changes Done:**
1. Added "Bearer " prefix before access token in Cli.java
2. For list `-l` parameter skip `oxd_id` validation.
=> Issue#329 - oxd: Getting Forbidden : 403 while using lsox script

oxd-common/src/main/java/org/gluu/oxd/common/params/GetAuthorizationUrlParams.java, oxd-gen-client/src/main/java/io/swagger/client/model/GetAuthorizationUrlParams.java, oxd-server/src/main/java/org/gluu/oxd/server/Utils.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetAuthorizationUrlOperation.java, oxd-server/src/main/resources/swagger.yaml, oxd-server/src/test/java/org/gluu/oxd/server/GetAuthorizationUrlTest.java
Issue#334 - Add `params` map to `/get-authorization-url` api 
https://github.com/GluuFederation/oxd/issues/334
=> Issue#334 - Add `params` map to `/get-authorization-url` api 

oxd-common/src/main/java/org/gluu/oxd/common/params/GetAuthorizationUrlParams.java, oxd-common/src/main/java/org/gluu/oxd/common/params/RpGetClaimsGatheringUrlParams.java, oxd-gen-client/src/main/java/io/swagger/client/model/GetAuthorizationUrlParams.java, oxd-gen-client/src/main/java/io/swagger/client/model/UmaRpGetClaimsGatheringUrlParams.java, oxd-gen-client/src/test/java/io/swagger/client/api/GetAuthorizationUrlTest.java, oxd-gen-client/src/test/java/io/swagger/client/api/UmaGetClaimsGatheringUrlTest.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetAuthorizationUrlOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/RpGetGetClaimsGatheringUrlOperation.java, oxd-server/src/main/resources/swagger.yaml, oxd-server/src/test/java/org/gluu/oxd/server/GetAuthorizationUrlTest.java, oxd-server/src/test/java/org/gluu/oxd/server/UmaGetClaimsGatheringUrlTest.java, oxd-server/src/test/resources/testng.xml
#130 - Enable client to set custom state value
https://github.com/GluuFederation/oxd/issues/130
=> #130 - Enable client to set custom state value

oxd-gen-client/src/test/java/io/swagger/client/api/GetUserInfoTest.java
#343 - Remove authorization_redirect_uri from /register-site command
https://github.com/GluuFederation/oxd/issues/343
=> #343 - Remove authorization_redirect_uri from /register-site command

oxd-server/src/main/java/org/gluu/oxd/server/op/RegisterSiteOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/UpdateSiteOperation.java
#354 - Unify parameters between /register-site and /update-site
https://github.com/GluuFederation/oxd/issues/354
=> #354 - Unify parameters between /register-site and /update-site

oxd-common/src/main/java/org/gluu/oxd/common/ErrorResponseCode.java, oxd-server/src/main/java/org/gluu/oxd/server/OxdServerConfiguration.java, oxd-server/src/main/java/org/gluu/oxd/server/op/RegisterSiteOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/service/DiscoveryService.java, oxd-server/src/main/java/org/gluu/oxd/server/service/ValidationService.java, oxd-server/src/main/resources/oxd-server.yml, oxd-server/src/test/resources/oxd-conf-test-h2-conf.json, oxd-server/src/test/resources/oxd-conf-test-redis.json, oxd-server/src/test/resources/oxd-conf-test.json, oxd-server/src/test/resources/oxd-server-dev.yml, oxd-server/src/test/resources/oxd-server-jenkins.yml, upgrade/oxd-server.yml.temp
#210 - Introduce ability to lock oxd to list of specific IDPs
https://github.com/GluuFederation/oxd/issues/210
=> #210 - Introduce ability to lock oxd to list of specific IDPs

oxd-server/src/main/java/org/gluu/oxd/server/op/RegisterSiteOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/UpdateSiteOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/service/Rp.java, oxd-server/src/main/resources/oxd-server.yml, oxd-server/src/test/resources/oxd-server-dev.yml, oxd-server/src/test/resources/oxd-server-jenkins.yml, upgrade/oxd-server.yml.temp
#50 - Provide fallback for all parameters
https://github.com/GluuFederation/oxd/issues/50
=> #50 - Provide fallback for all parameters

oxd-server/src/main/java/org/gluu/oxd/server/op/AuthorizationCodeFlowOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetAuthorizationCodeOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetTokensByCodeOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/ImplicitFlowOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/service/UmaTokenService.java
#373 - Drop `ClientUtils.showClient(tokenClient);` from oxd.
https://github.com/GluuFederation/oxd/issues/373
=> #373 - Drop `ClientUtils.showClient(tokenClient);` from oxd.

oxd-server/pom.xml, oxd-server/src/main/java/org/gluu/oxd/server/HttpException.java, oxd-server/src/main/java/org/gluu/oxd/server/OxdServerApplication.java, oxd-server/src/main/java/org/gluu/oxd/server/OxdServerConfiguration.java, oxd-server/src/main/java/org/gluu/oxd/server/RestResource.java, oxd-server/src/main/java/org/gluu/oxd/server/TracingUtil.java, oxd-server/src/main/resources/oxd-server.yml, oxd-server/src/test/resources/oxd-conf-test-h2-conf.json, oxd-server/src/test/resources/oxd-conf-test-redis.json, oxd-server/src/test/resources/oxd-conf-test.json, oxd-server/src/test/resources/oxd-server-dev.yml, oxd-server/src/test/resources/oxd-server-jenkins.yml, upgrade/oxd-server.yml.temp
#182 - Add tracing metrics to oxd server
https://github.com/GluuFederation/oxd/issues/182
=> #182 - Add tracing metrics to oxd server

oxd-server/src/main/java/org/gluu/oxd/server/OxdServerConfiguration.java, oxd-server/src/main/java/org/gluu/oxd/server/mapper/RegisterRequestMapper.java, oxd-server/src/main/java/org/gluu/oxd/server/service/RpService.java, oxd-server/src/main/resources/oxd-server.yml, oxd-server/src/test/resources/oxd-conf-test-h2-conf.json, oxd-server/src/test/resources/oxd-conf-test-redis.json, oxd-server/src/test/resources/oxd-conf-test.json, oxd-server/src/test/resources/oxd-server-dev.yml, oxd-server/src/test/resources/oxd-server-jenkins.yml, upgrade/oxd-server.yml.temp
#389 - HA : RpService should cache Rp object for configurable amount of time (not indefinitely).
https://github.com/GluuFederation/oxd/issues/389
=> #389 - HA : RpService should cache Rp object for configurable amount of time (not indefinitely).

oxd-common/src/main/java/org/gluu/oxd/common/ExpiredObject.java, oxd-common/src/main/java/org/gluu/oxd/common/ExpiredObjectType.java, oxd-common/src/main/java/org/gluu/oxd/common/Jackson2.java, oxd-server/src/main/java/org/gluu/oxd/server/OxdServerConfiguration.java, oxd-server/src/main/java/org/gluu/oxd/server/Utils.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetTokensByCodeOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/ValidateOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/Validator.java, oxd-server/src/main/java/org/gluu/oxd/server/persistence/PersistenceService.java, oxd-server/src/main/java/org/gluu/oxd/server/persistence/PersistenceServiceImpl.java, oxd-server/src/main/java/org/gluu/oxd/server/persistence/RedisPersistenceService.java, oxd-server/src/main/java/org/gluu/oxd/server/persistence/SqlPersistenceServiceImpl.java, oxd-server/src/main/java/org/gluu/oxd/server/service/StateService.java, oxd-server/src/main/resources/oxd-server.yml, oxd-server/src/test/resources/oxd-conf-test-h2-conf.json, oxd-server/src/test/resources/oxd-conf-test-redis.json, oxd-server/src/test/resources/oxd-conf-test.json, oxd-server/src/test/resources/oxd-server-dev.yml, oxd-server/src/test/resources/oxd-server-jenkins.yml, upgrade/oxd-server.yml.temp
#387 - `StateService` keeps state and nonce in-memory which prevents HA of oxd.
https://github.com/GluuFederation/oxd/issues/387
=> #387 - `StateService` keeps state and nonce in-memory which prevents HA of oxd.

oxd-common/src/main/java/org/gluu/oxd/common/params/RegisterSiteParams.java, oxd-common/src/main/java/org/gluu/oxd/common/params/UpdateSiteParams.java, oxd-gen-client/src/main/java/io/swagger/client/model/RegisterSiteParams.java, oxd-gen-client/src/main/java/io/swagger/client/model/UpdateSiteParams.java, oxd-server/src/main/java/org/gluu/oxd/server/Utils.java, oxd-server/src/main/java/org/gluu/oxd/server/guice/GuiceModule.java, oxd-server/src/main/java/org/gluu/oxd/server/mapper/RegisterResponseMapper.java, oxd-server/src/main/java/org/gluu/oxd/server/op/RegisterSiteOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/service/Rp.java, oxd-server/src/main/java/org/gluu/oxd/server/service/RpService.java, oxd-server/src/main/java/org/gluu/oxd/server/service/RpSyncService.java, oxd-server/src/main/resources/swagger.yaml, oxd-server/src/test/java/org/gluu/oxd/server/TestUtils.java, oxd-server/src/test/java/org/gluu/oxd/server/service/RpServiceTest.java, oxd-server/src/test/java/org/gluu/oxd/server/service/RpSyncServiceTest.java, oxd-server/src/test/resources/testng.xml
#390 - Sync client from OP : Update oxd database by reading client, Part - I
https://github.com/GluuFederation/oxd/issues/390
=> #390 - Sync client from OP : Update oxd database by reading client, Part - I

oxd-server/src/main/java/org/gluu/oxd/server/Cli.java, oxd-server/src/main/java/org/gluu/oxd/server/mapper/RegisterRequestMapper.java, oxd-server/src/main/java/org/gluu/oxd/server/mapper/RegisterResponseMapper.java, oxd-server/src/main/java/org/gluu/oxd/server/op/BaseOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetRpOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/service/DiscoveryService.java, oxd-server/src/main/java/org/gluu/oxd/server/service/RpSyncService.java, oxd-server/src/main/java/org/gluu/oxd/server/service/UmaTokenService.java, oxd-server/src/main/java/org/gluu/oxd/server/service/ValidationService.java, oxd-server/src/test/java/org/gluu/oxd/server/GetAuthorizationUrlTest.java, oxd-server/src/test/java/org/gluu/oxd/server/GetLogoutUrlTest.java, oxd-server/src/test/java/org/gluu/oxd/server/RegisterSiteTest.java, oxd-server/src/test/java/org/gluu/oxd/server/service/RpSyncServiceTest.java
#390 - Sync client from OP : Update oxd database by reading client, Part 2
https://github.com/GluuFederation/oxd/issues/390
=> #390 - Sync client from OP : Update oxd database by reading client, Part 2

oxd-common/src/main/java/org/gluu/oxd/common/ErrorResponseCode.java, oxd-server/src/main/java/org/gluu/oxd/server/op/CheckIdTokenOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetTokensByCodeOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/JwsSignerObject.java, oxd-server/src/main/java/org/gluu/oxd/server/op/ValidateOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/Validator.java, oxd-server/src/test/java/org/gluu/oxd/server/GetTokensByCodeTest.java, oxd-server/src/test/java/org/gluu/oxd/server/RegisterSiteTest.java, oxd-server/src/test/java/org/gluu/oxd/server/service/ValidatorTest.java, oxd-server/src/test/resources/testng.xml
#400 - Check and add to validation missed steps if identified
https://github.com/GluuFederation/oxd/issues/400
1. Added validation for `azp` claim
2. Added `HMACSigner` and `ECDSASigner` for their algos.
=> #400 - Check and add to validation missed steps if identified

oxd-server/src/main/java/org/gluu/oxd/server/op/CheckIdTokenOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetAuthorizationCodeOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetAuthorizationUrlOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetLogoutUrlOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetTokensByCodeOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/RsCheckAccessOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/RsModifyOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/RsProtectOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/ValidateOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/service/DiscoveryService.java, oxd-server/src/main/java/org/gluu/oxd/server/service/UmaTokenService.java
#402 - Rename `site -> rp` except persistence.
https://github.com/GluuFederation/oxd/issues/402
=> #402 - Rename `site -> rp` except persistence.

oxd-server/src/main/java/org/gluu/oxd/server/op/RsModifyOperation.java
#363 - Introduce new `/uma-rs-modify` command to be able modify existing resource
https://github.com/GluuFederation/oxd/issues/363
Made following corrections in `/uma-rs-modify`
1. We have set ticketScopes to Rp saved in oxd.
2. When saving resource with `scope_expression` to OP, the `scopes` parameter should also be set.
=> #363 - Introduce new `/uma-rs-modify` command to be able modify existing resource

oxd-common/src/test/java/org/gluu/oxd/common/SeleniumTestUtils.java, oxd-gen-client/src/test/java/io/swagger/client/api/GetTokensByCodeTest.java, oxd-server/src/main/resources/swagger.yaml, oxd-server/src/test/java/org/gluu/oxd/server/GetTokensByCodeTest.java, oxd-server/src/test/java/org/gluu/oxd/server/RegisterSiteTest.java, oxd-server/src/test/java/org/gluu/oxd/server/SpontaneousScopeAuthTest.java, oxd-server/src/test/java/org/gluu/oxd/server/UmaSpontaneousScopeTest.java, oxd-server/src/test/resources/testng.xml
#409 - Add spontaneous scopes to oxd
https://github.com/GluuFederation/oxd/issues/409
=> #409 - Add spontaneous scopes to oxd

oxd-server/src/main/java/org/gluu/oxd/server/op/RsModifyOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/RsProtectOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/service/DiscoveryService.java, oxd-server/src/main/java/org/gluu/oxd/server/service/HttpService.java
#423 - Fix oxd after httpclient upgrade in oxauth
https://github.com/GluuFederation/oxd/issues/423
=> #423 - Fix oxd after httpclient upgrade in oxauth

oxd-common/src/main/java/org/gluu/oxd/common/params/RpGetClaimsGatheringUrlParams.java, oxd-gen-client/src/main/java/io/swagger/client/model/UmaRpGetClaimsGatheringUrlParams.java, oxd-gen-client/src/test/java/io/swagger/client/api/UmaGetClaimsGatheringUrlTest.java, oxd-server/src/main/java/org/gluu/oxd/server/op/RpGetGetClaimsGatheringUrlOperation.java, oxd-server/src/main/resources/swagger.yaml, oxd-server/src/test/java/org/gluu/oxd/server/UmaGetClaimsGatheringUrlTest.java
#91 - UMA 2 : add custom redirect parameters to get_claims_gathering_url command
https://github.com/GluuFederation/oxd/issues/91
=> #91 - UMA 2 : add custom redirect parameters to get_claims_gathering_url command

oxd-common/src/main/java/org/gluu/oxd/common/ErrorResponseCode.java, oxd-server/pom.xml, oxd-server/src/main/bin/lsox.bat, oxd-server/src/main/bin/lsox.sh, oxd-server/src/main/bin/oxd-start-console.bat, oxd-server/src/main/bin/oxd-start.bat, oxd-server/src/main/bin/oxd-start.sh, oxd-server/src/main/java/org/gluu/oxd/server/guice/GuiceModule.java, oxd-server/src/main/java/org/gluu/oxd/server/persistence/H2PersistenceProvider.java, oxd-server/src/main/java/org/gluu/oxd/server/persistence/JDBCConfiguration.java, oxd-server/src/main/java/org/gluu/oxd/server/persistence/JDBCPersistenceProvider.java, oxd-server/src/main/java/org/gluu/oxd/server/persistence/PersistenceServiceImpl.java, oxd-server/src/main/java/org/gluu/oxd/server/persistence/SqlPersistenceServiceImpl.java
#430 - Add support for JDBC connection to be able connect to any RDBMS
https://github.com/GluuFederation/oxd/issues/430
=> #430 - Add support for JDBC connection to be able connect to any RDBMS

oxd-server/src/main/java/org/gluu/oxd/server/persistence/PersistenceServiceImpl.java, oxd-server/src/main/java/org/gluu/oxd/server/persistence/SqlPersistenceServiceImpl.java
#430 - Add support for JDBC connection to be able connect to any RDBMS 
https://github.com/GluuFederation/oxd/issues/430
Adjusting code to use `key` column in Mysql database by enclosing key with ` character for Mysql db
=> #430 - Adjusting code to use `key` column in Mysql database

oxd-server/src/test/java/org/gluu/oxd/mock/guice/MockAppModule.java, oxd-server/src/test/java/org/gluu/oxd/mock/service/OpClientFactoryMockImpl.java
#374 - Use cached mocked objects in OpClientFactoryMockImpl.
https://github.com/GluuFederation/oxd/issues/374
=> #374 - Use cached mocked objects in OpClientFactoryMockImpl.

oxd-common/src/main/java/org/gluu/oxd/common/ErrorResponseCode.java, oxd-server/src/main/java/org/gluu/oxd/server/op/Validator.java
#440 - Identify the missing 'sub' value and reject the ID Token.
https://github.com/GluuFederation/oxd/issues/440
=> #440 - Identify the missing 'sub' value and reject the ID Token.

oxd-common/src/main/java/org/gluu/oxd/common/ErrorResponseCode.java, oxd-server/src/main/java/org/gluu/oxd/server/op/Validator.java, oxd-server/src/main/java/org/gluu/oxd/server/service/PublicOpKeyService.java
#442 - If kid is absent in ID_TOKEN header then the matching key out of the Issuer's published set
https://github.com/GluuFederation/oxd/issues/442
=> #442 - If kid is absent in ID_TOKEN header then the matching key out of the Issuer's published set

oxd-server/src/main/java/org/gluu/oxd/server/mapper/RegisterRequestMapper.java, oxd-server/src/main/java/org/gluu/oxd/server/op/RegisterSiteOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/UpdateSiteOperation.java
https://github.com/GluuFederation/oxd/issues/451
=> #451 - Fix client registration request where response_types sent in ['code', 'code id_token', 'code token']

oxd-common/src/main/java/org/gluu/oxd/common/ErrorResponseCode.java, oxd-common/src/main/java/org/gluu/oxd/common/params/CheckIdTokenParams.java, oxd-server/src/main/java/org/gluu/oxd/server/op/CheckIdTokenOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/Validator.java
#453 - Verify the `c_hash` presence in the returned ID token for 'code id_token' and 'code id_token token' hybrid flow.
https://github.com/GluuFederation/oxd/issues/453
=> #453 - Verify the `c_hash` presence in the returned ID token for 'code id_token' and 'code id_token token' hybrid flow.

oxd-common/src/main/java/org/gluu/oxd/common/ErrorResponseCode.java, oxd-common/src/main/java/org/gluu/oxd/common/params/CheckIdTokenParams.java, oxd-server/src/main/java/org/gluu/oxd/server/OxdServerConfiguration.java, oxd-server/src/main/java/org/gluu/oxd/server/op/CheckIdTokenOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/Validator.java
#454 - Verify the `at_hash` presence in the ID_token for 'id_token token' (Implicit) and 'code id_token token' (hybrid) flow.
https://github.com/GluuFederation/oxd/issues/454
=> #454 - Verify the `at_hash` presence in the ID_token for 'id_token token' (Implicit) and 'code id_token token' (hybrid) flow.

oxd-server/src/main/java/org/gluu/oxd/server/op/GetUserInfoOperation.java
#449 - Adding some logs.
https://github.com/GluuFederation/oxd/issues/449
=> #449 - Adding some logs.

oxd-server/src/main/java/org/gluu/oxd/server/op/GetUserInfoOperation.java
=> #449 - beautifying the log.

oxd-common/src/main/java/org/gluu/oxd/common/params/GetUserInfoParams.java, oxd-gen-client/src/main/java/io/swagger/client/model/GetUserInfoParams.java, oxd-gen-client/src/test/java/io/swagger/client/api/GetUserInfoTest.java, oxd-server/src/main/java/org/gluu/oxd/server/OxdServerConfiguration.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetUserInfoOperation.java, oxd-server/src/main/resources/swagger.yaml, oxd-server/src/test/java/org/gluu/oxd/server/GetUserInfoTest.java, oxd-server/src/test/resources/oxd-server-jenkins.yml
#441 - Identify the invalid 'sub' value and reject the UserInfo Response.
https://github.com/GluuFederation/oxd/issues/441
=> #441 - Identify the invalid 'sub' value and reject the UserInfo Response.

oxd-gen-client/src/test/java/io/swagger/client/api/GetLogoutUrlTest.java, oxd-gen-client/src/test/java/io/swagger/client/api/IntrospectAccessTokenTest.java, oxd-gen-client/src/test/java/io/swagger/client/api/RpGetRptTest.java, oxd-gen-client/src/test/java/io/swagger/client/api/RsCheckAccessTest.java, oxd-gen-client/src/test/java/io/swagger/client/api/RsModifyTest.java, oxd-gen-client/src/test/java/io/swagger/client/api/RsProtectTest.java, oxd-gen-client/src/test/java/io/swagger/client/api/UmaFullTest.java, oxd-gen-client/src/test/java/io/swagger/client/api/UmaGetClaimsGatheringUrlTest.java
Correcting Test cases
https://github.com/GluuFederation/oxd/issues/466
=> #466 - Correcting Test cases

oxd-server/pom.xml, oxd-server/src/main/assembly/windows-exe-src.xml
#474 - Configuration changes for oxd Windows service installer
https://github.com/GluuFederation/oxd/issues/474
=> #474 - Configuration changes for oxd Windows service installer

oxd-server/pom.xml
#478 - Read jedis version from `gluu-core-bom`
https://support.gluu.org/8372/
=> #478 - Read jedis version from `gluu-core-bom`

oxd-server/pom.xml
#478 - Read jedis version from `gluu-core-bom` 
https://github.com/GluuFederation/oxd/issues/478
=> #478 - Read jedis version from `gluu-core-bom` 

oxd-server/src/main/java/org/gluu/oxd/server/op/RsProtectOperation.java
423 - Fix oxd after httpclient upgrade in oxauth
https://github.com/GluuFederation/oxd/issues/423
=> 423 - Fix oxd after httpclient upgrade in oxauth

oxd-common/pom.xml, oxd-server/pom.xml, oxd-server/src/main/java/org/gluu/oxd/server/op/RegisterSiteOperation.java, pom.xml
#484 - Upgrade oxd to log4j version 2
GluuFederation/oxd#484
=> #484 - Upgrade oxd to log4j version 2

oxd-common/src/main/java/org/gluu/oxd/common/CoreUtils.java, oxd-server/src/main/java/org/gluu/oxd/server/service/HttpService.java
#490 - `trust_all_certs` feature in oxd-server.yml not working
https://github.com/GluuFederation/oxd/issues/490
=> #490 - `trust_all_certs` feature in oxd-server.yml not working

oxd-common/src/main/java/org/gluu/oxd/common/ErrorResponseCode.java, oxd-server/src/main/java/org/gluu/oxd/server/op/RegisterSiteOperation.java
#486 - Improve error message when client_secret is not returned by OP
https://github.com/GluuFederation/oxd/issues/486
=> #486 - Improve error message when client_secret is not returned by OP

oxd-server/src/main/java/org/gluu/oxd/server/persistence/providers/GluuPersistenceConfiguration.java
=> correcting error message

pom.xml
#501 - Correct security alert in test dependency
https://github.com/GluuFederation/oxd/issues/501
=> #501 - Correct security alert in test dependency

oxd-common/pom.xml, oxd-common/src/test/java/org/gluu/oxd/common/SeleniumTestUtils.java, oxd-server/pom.xml, pom.xml
#501 - Correct security alert in test dependency 
https://github.com/GluuFederation/oxd/issues/501
=> #501 - Correct security alert in test dependency 

oxd-common/src/main/java/org/gluu/oxd/common/ErrorResponseCode.java, oxd-server/src/main/java/org/gluu/oxd/server/OxdServerConfiguration.java, oxd-server/src/main/java/org/gluu/oxd/server/RestResource.java
#503 - Add `bindHost` with default value localhost
https://github.com/GluuFederation/oxd/issues/503
=> #503 - Add `bindHost` with default value localhost

oxd-server/src/main/assembly/src.xml, oxd-server/src/main/assembly/windows-exe-src.xml, oxd-server/src/main/resources/windows/generate-exe-using-bat.iss
#499 - Passing `Request Object by Value` and `Request Object by Reference` in Authorization Request
=> #499 - Passing `Request Object by Value` and `Request Object by Reference` in Authorization Request

oxd-server/pom.xml, pom.xml
#512 - Upgrade dropwizard to version: 2.0.3
=> #512 - Upgrade dropwizard to version: 2.0.3

oxd-server/pom.xml
#512 - Upgrade dropwizard to version: 2.0.12 #512
https://github.com/GluuFederation/oxd/issues/512
=> #512 - Upgrade dropwizard to version: 2.0.12 #512

oxd-server/src/test/java/org/gluu/oxd/server/RsCheckAccessTest.java, oxd-server/src/test/java/org/gluu/oxd/server/RsModifyTest.java, oxd-server/src/test/java/org/gluu/oxd/server/service/RpServiceTest.java
#512 - Upgrade dropwizard to version: 2.0.12
https://github.com/GluuFederation/oxd/issues/512
=> #512 - Upgrade dropwizard to version: 2.0.12

pom.xml
=> #512 - Adding jackson bom

oxd-common/src/main/java/org/gluu/oxd/common/CoreUtils.java, oxd-server/src/main/java/org/gluu/oxd/server/OxdServerConfiguration.java, oxd-server/src/main/java/org/gluu/oxd/server/service/HttpService.java
#517 - Add fields to select `tlsVersion` and `ciphers` in oxd configuration
https://github.com/GluuFederation/oxd/issues/517
=> #517 - Add fields to select `tlsVersion` and `ciphers` in oxd configuration

oxd-common/src/main/java/org/gluu/oxd/common/ErrorResponseCode.java, oxd-common/src/main/java/org/gluu/oxd/common/params/GetAuthorizationCodeParams.java, oxd-common/src/main/java/org/gluu/oxd/common/params/GetTokensByCodeParams.java, oxd-gen-client/src/main/java/io/swagger/client/model/GetTokensByCodeParams.java, oxd-gen-client/src/test/java/io/swagger/client/api/GetTokensByCodeTest.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetTokensByCodeOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/service/KeyGeneratorService.java, oxd-server/src/main/resources/swagger.yaml, oxd-server/src/test/java/org/gluu/oxd/server/GetTokensByCodeTest.java
#511 - Add `client_assertion`, `TokenEndpointAuthSigningAlgorithm` params in ` /get-tokens-by-code`.
https://github.com/GluuFederation/oxd/issues/511
=> #511 - Add `client_assertion`, `TokenEndpointAuthSigningAlgorithm` params in ` /get-tokens-by-code`.

oxd-gen-client/src/test/java/io/swagger/client/api/GetTokensByCodeTest.java, oxd-gen-client/src/test/java/io/swagger/client/api/GetUserInfoTest.java, oxd-gen-client/src/test/java/io/swagger/client/api/RegisterSiteTest.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetClientTokenOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetTokensByCodeOperation.java, oxd-server/src/test/java/org/gluu/oxd/server/GetTokensByCodeTest.java, oxd-server/src/test/java/org/gluu/oxd/server/GetUserInfoTest.java, oxd-server/src/test/java/org/gluu/oxd/server/RegisterSiteTest.java
https://github.com/GluuFederation/oxd/issues/511
=> #511 - Fixing test cases

oxd-server/src/main/java/org/gluu/oxd/server/OxdServerConfiguration.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetAuthorizationUrlOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetLogoutUrlOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetTokensByCodeOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/RpGetGetClaimsGatheringUrlOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/service/StateService.java, oxd-server/src/test/java/org/gluu/oxd/server/CheckAccessTokenTest.java, oxd-server/src/test/java/org/gluu/oxd/server/CheckIdTokenTest.java, oxd-server/src/test/java/org/gluu/oxd/server/GetTokensByCodeTest.java
#538 - Write test with state=base64urlencode(url) (version_4.2.1)
https://github.com/GluuFederation/oxd/issues/538
=> #538 - Write test with state=base64urlencode(url) (version_4.2.1)

oxd-server/src/main/java/org/gluu/oxd/server/OxdServerConfiguration.java, oxd-server/src/main/java/org/gluu/oxd/server/Utils.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetAuthorizationUrlOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetLogoutUrlOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/GetTokensByCodeOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/RpGetGetClaimsGatheringUrlOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/service/StateService.java, oxd-server/src/test/java/org/gluu/oxd/server/CheckAccessTokenTest.java, oxd-server/src/test/java/org/gluu/oxd/server/CheckIdTokenTest.java, oxd-server/src/test/java/org/gluu/oxd/server/GetTokensByCodeTest.java
#538 - Write test with state=base64urlencode(url)
https://github.com/GluuFederation/oxd/issues/538
=> #538 - Write test with state=base64urlencode(url)

oxd-server/src/main/java/org/gluu/oxd/server/OxdServerConfiguration.java, oxd-server/src/main/java/org/gluu/oxd/server/op/Validator.java, oxd-server/src/main/java/org/gluu/oxd/server/service/PublicOpKeyService.java
https://github.com/GluuFederation/oxd/issues/543
=> #543 - Validate id_token signature: Refresh jwks keys from server only if it is allowed

oxd-server/src/main/java/org/gluu/oxd/server/op/GetLogoutUrlOperation.java
#550 - Add `id_token_hint` parameter in LogoutUrl
https://github.com/GluuFederation/oxd/issues/550
=> #550 - Add `id_token_hint` parameter in LogoutUrl

debian/oxd-server, oxd-server/pom.xml, oxd-server/src/main/java/org/gluu/oxd/server/RestResource.java, oxd-server/src/main/java/org/gluu/oxd/server/ServerLauncher.java, oxd-server/src/main/java/org/gluu/oxd/server/Utils.java, pom.xml
#560 - Displaying oxd version in `/health-check` and `/opt/oxd-server/bin/oxd-server version` output
https://github.com/GluuFederation/oxd/issues/560
=> #560 - Displaying oxd version in `/health-check` and `/opt/oxd-server/bin/oxd-server version` output

pom.xml
fixes  GluuFederation/oxd #562
=> fix ReasonPhrase:HTTPS Required for dependency downloads

oxd-client/src/main/java/org/gluu/oxd/client/ClientInterface.java, oxd-common/src/main/java/org/gluu/oxd/common/CommandType.java, oxd-common/src/main/java/org/gluu/oxd/common/ErrorResponseCode.java, oxd-common/src/main/java/org/gluu/oxd/common/params/ThirdPartyLoginParams.java, oxd-common/src/main/java/org/gluu/oxd/common/response/RegisterSiteResponse.java, oxd-server/src/main/java/org/gluu/oxd/server/RestResource.java, oxd-server/src/main/java/org/gluu/oxd/server/op/InitiateThirdPartyLoginOperation.java, oxd-server/src/main/java/org/gluu/oxd/server/op/OperationFactory.java, oxd-server/src/main/java/org/gluu/oxd/server/op/RegisterSiteOperation.java, oxd-server/src/test/java/org/gluu/oxd/server/RegisterSiteTest.java, oxd-server/src/test/java/org/gluu/oxd/server/ThirdPartyLoginTest.java, oxd-server/src/test/resources/testng.xml
…om a Third Party
https://github.com/GluuFederation/oxd/issues/565
=> #565 - Create `login initiation endpoint` in oxd to initiate Login from a Third Party

oxd-server/pom.xml, pom.xml
https://github.com/GluuFederation/oxd/issues/629
=> chore: Version 4.5.3 libs update
