GluuFederation/oxd

oxd-common/src/main/java/org/xdi/oxd/common/response/GetClientTokenResponse.java
oxd-gen-client/src/main/java/io/swagger/client/model/GetClientTokenResponseData.java
oxd-gen-client/src/main/java/io/swagger/client/model/UpdateSiteResponseData.java
oxd-gen-client/src/test/java/io/swagger/client/api/BaseTestCase.java
oxd-gen-client/src/test/java/io/swagger/client/api/EnabledProtectionAccessToken.java
oxd-gen-client/src/test/java/io/swagger/client/api/GetClientTokenTest.java
oxd-gen-client/src/test/java/io/swagger/client/api/IntrospectAccessTokenTest.java
oxd-gen-client/src/test/java/io/swagger/client/api/ProtectionAccessTokenRequired.java
oxd-gen-client/src/test/java/io/swagger/client/api/RegisterSiteTest.java
oxd-gen-client/src/test/java/io/swagger/client/api/RemoveSiteTest.java
oxd-gen-client/src/test/java/io/swagger/client/api/SetUpTest.java
oxd-gen-client/src/test/java/io/swagger/client/api/TestMethodListener.java
oxd-gen-client/src/test/java/io/swagger/client/api/Tester.java
oxd-server/src/main/java/org/xdi/oxd/server/Utils.java
oxd-server/src/main/java/org/xdi/oxd/server/op/GetAccessTokenByRefreshTokenOperation.java
oxd-server/src/main/java/org/xdi/oxd/server/op/GetClientTokenOperation.java
oxd-server/src/main/resources/swagger.yaml
oxd-server/src/test/java/org/xdi/oxd/server/IntrospectAccessTokenTest.java
oxd-server/src/test/java/org/xdi/oxd/server/SetUpTest.java
oxd-server/src/test/resources/testng.xml

Tests for client token and introspect token based on swagger client have been developed. As some tests work only when protection command access token is enabled, so some functionality has been added to skip the tests when the configuration doesn't match.

Added Client token and Introspect token test for swagger

---

oxd-server/src/main/resources/oxd-server.yml
oxd-server/src/test/resources/oxd-server-dev.yml
oxd-server/src/test/resources/oxd-server-jenkins.yml

#332 - oxd-4.0: Remove redundant Logger-specific levels (`Trace`) from oxd-server.yml
https://github.com/GluuFederation/oxd/issues/332

#332 - oxd-4.0: Remove redundant Logger-specific levels (`Trace`) from oxd-server.yml

---

oxd-gen-client/src/main/java/io/swagger/client/model/RegisterSiteParams.java
oxd-gen-client/src/main/java/io/swagger/client/model/RegistersiteCustomAttributes.java
oxd-gen-client/src/test/java/io/swagger/client/api/RegisterSiteTest.java
oxd-server/src/main/resources/swagger.yaml

Issue#338 - add `idTokenSignedResponseAlg` to `/register-site` command
https://github.com/GluuFederation/oxd/issues/338
Due to some confusion earlier I did not include below fields in swaggers specs and codegen-generated client. Now all fields have been included.
Fields:
client_token_endpoint_auth_signing_alg
idTokenEncryptedResponseAlg
idTokenEncryptedResponseEnc
userInfoSignedResponseAlg
userInfoEncryptedResponseAlg
userInfoEncryptedResponseEnc
requestObjectSigningAlg
requestObjectEncryptionAlg
requestObjectEncryptionEnc

Issue#338 - add `idTokenSignedResponseAlg` to `/register-site` command

---

oxd-server/src/main/java/org/gluu/oxd/server/op/RegisterSiteOperation.java
oxd-server/src/main/java/org/gluu/oxd/server/op/UpdateSiteOperation.java

#343 - Remove authorization_redirect_uri from /register-site command
https://github.com/GluuFederation/oxd/issues/343
I found that when adding `redirect_uris` to set the urls are not added in same order in HashSet.
So when testing with different URLs often it didnot redirect to first url. 
So we have used LinkedHshSet to maintain the same order.

#343 - Remove authorization_redirect_uri from /register-site command

---

oxd-server/src/main/java/org/gluu/oxd/server/op/RegisterSiteOperation.java
oxd-server/src/main/java/org/gluu/oxd/server/op/UpdateSiteOperation.java

#162 - Add description and oxdID to client metadata
https://github.com/GluuFederation/oxd/issues/162

#162 - Add description and oxdID to client metadata

---

oxd-common/src/main/java/org/gluu/oxd/common/Jackson2.java
oxd-server/src/main/java/org/gluu/oxd/server/persistence/RedisPersistenceService.java
oxd-server/src/main/java/org/gluu/oxd/server/persistence/SqlPersistenceServiceImpl.java
oxd-server/src/main/java/org/gluu/oxd/server/service/Rp.java
oxd-server/src/main/java/org/gluu/oxd/server/service/UmaTokenService.java
oxd-server/src/test/java/org/gluu/oxd/server/service/RpServiceTest.java
oxd-server/src/test/resources/testng.xml

#371 - Persist field only if it's not null into oxd db to avoid saving redundant data
https://github.com/GluuFederation/oxd/issues/371
Note : Added both JsonInclude.Include.NON_NULL and JsonInclude.Include.NON_EMPTY. JsonInclude.Include.NON_EMPTY added to remove empty strings and array.

#371 - Persist field only if it's not null into oxd db to avoid saving redundant data

---

oxd-server/src/main/java/org/gluu/oxd/server/op/UpdateSiteOperation.java

#379 - Incorrect scopes are added when client is updated using `/update-site` command
https://github.com/GluuFederation/oxd/issues/379

#379 - Incorrect scopes are added when client is updated using `/update-site` command

---

oxd-common/src/main/java/org/gluu/oxd/common/params/RegisterSiteParams.java
oxd-common/src/main/java/org/gluu/oxd/common/params/UpdateSiteParams.java
oxd-gen-client/src/main/java/io/swagger/client/model/RegisterSiteParams.java
oxd-gen-client/src/main/java/io/swagger/client/model/UpdateSiteParams.java
oxd-server/src/main/java/org/gluu/oxd/server/mapper/RegisterRequestMapper.java
oxd-server/src/main/java/org/gluu/oxd/server/op/RegisterSiteOperation.java
oxd-server/src/main/java/org/gluu/oxd/server/op/UpdateSiteOperation.java
oxd-server/src/main/java/org/gluu/oxd/server/service/Rp.java
oxd-server/src/main/resources/swagger.yaml

#409 - Add spontaneous scopes to oxd
https://github.com/GluuFederation/oxd/issues/409
In this PR we have added below params to `/register-site` and `/update-site`
----------------------------
allow_spontaneous_scopes - boolean, whether to allow spontaneous scopes for client
spontaneous_scopes - list of spontaneous scopes (regexp against which validation is performed)

#409 - Add spontaneous scopes to oxd, Part 1

---

oxd-gen-client/pom.xml
oxd-server/src/main/resources/swagger.yaml

#417 - Correcting licence document link in source code (`branch: version_4.0`)
https://github.com/GluuFederation/oxd/issues/417

#417 - Correcting licence document link in source code (`branch: version_4.0`)

---

oxd-gen-client/pom.xml
oxd-server/src/main/resources/swagger.yaml

#417 - Correcting licence document link in source code (`branch: version_4.1`)
https://github.com/GluuFederation/oxd/issues/417

#417 - Correcting licence document link in source code (`branch: version_4.1`)

---

oxd-gen-client/pom.xml
oxd-server/src/main/resources/swagger.yaml

#417 - Correcting licence document link in source code (`branch: version_4.0.1`)
https://github.com/GluuFederation/oxd/issues/417

#417 - Correcting licence document link in source code (`branch: version_4.0.1`)

---

oxd-server/src/main/java/org/gluu/oxd/server/op/RsProtectOperation.java

https://github.com/GluuFederation/oxd/issues/423
Initializing `UmaResourceService`  outside loop to avoid re-creation of service.

#423 - Fix oxd after httpclient upgrade in oxauth

---

oxd-server/src/test/jmeter/oxd-test-with-mocked-op-clients.jmx

#372 - Performance : oxd under high load has problem with `state` validation.
https://github.com/GluuFederation/oxd/issues/372
This issue was due to the same `state` value for each thread. Due to this `state` created by one thread was deleted by another thread causing `bad request`. We have added a counter value each thread `state`

#372 - Performance : oxd under high load has problem with `state` validation.

---

oxd-common/src/main/java/org/gluu/oxd/common/ErrorResponseCode.java
oxd-server/src/main/java/org/gluu/oxd/server/op/Validator.java

#438 - If 'iat' value is missing from `ID_TOKEN` then `ID_TOKEN` should be rejected during token validation.
https://github.com/GluuFederation/oxd/issues/438

#438 - If 'iat' value is missing from `ID_TOKEN` then `ID_TOKEN` should be rejected during token validation.

---

oxd-common/src/main/java/org/gluu/oxd/common/ErrorResponseCode.java
oxd-server/src/main/java/org/gluu/oxd/server/op/GetUserInfoOperation.java

#441 - Identify the invalid 'sub' value and reject the UserInfo Response.
https://github.com/GluuFederation/oxd/issues/441

#441 - Identify the invalid 'sub' value and reject the UserInfo Response.

---

oxd-server/src/main/java/org/gluu/oxd/server/op/GetUserInfoOperation.java

#441 - Identify the invalid 'sub' value and reject the UserInfo Response
https://github.com/GluuFederation/oxd/issues/441
Correcting the test case by validating the subject_identifier of an only successful response.

#441 - Identify the invalid 'sub' value and reject the UserInfo Response

---

oxd-common/src/main/java/org/gluu/oxd/common/params/GetAuthorizationUrlParams.java
oxd-gen-client/src/main/java/io/swagger/client/model/GetAuthorizationUrlParams.java
oxd-gen-client/src/test/java/io/swagger/client/api/GetAuthorizationUrlTest.java
oxd-server/src/main/java/org/gluu/oxd/server/op/CheckIdTokenOperation.java
oxd-server/src/main/java/org/gluu/oxd/server/op/GetAuthorizationUrlOperation.java
oxd-server/src/main/java/org/gluu/oxd/server/op/Validator.java
oxd-server/src/main/resources/swagger.yaml
oxd-server/src/test/java/org/gluu/oxd/server/GetAuthorizationUrlTest.java

#449 - Adding `nonce` request parameter to explicitly pass `nonce` value to Authentication Request.
https://github.com/GluuFederation/oxd/issues/449

#449 - Adding `nonce` request parameter to explicitly pass `nonce` value to Authentication Request.

---

oxd-server/src/main/java/org/gluu/oxd/server/RestResource.java

#464 - Make `Bearer` case insensitive in oxd
https://github.com/GluuFederation/oxd/issues/464

#464 - Make `Bearer` case insensitive in oxd

---

oxd-server/src/test/java/org/gluu/oxd/server/RegisterSiteTest.java

#466 - Support different AS for `access_token` validation (other then the one processing API call)
https://github.com/GluuFederation/oxd/issues/466

#466 - Support different AS for `access_token` validation (other then the one processing API call)

---

oxd-server/src/main/java/org/gluu/oxd/server/service/Rp.java

#471 - Set default `sync_client_from_op` and `sync_client_period_in_econds` when RP for clients created using oxd version <= 4.1
https://github.com/GluuFederation/oxd/issues/471

#471 - Set default `sync_client_from_op` and `sync_client_period_in_econds` when clients created using oxd version <= 4.1 and used in version4.2

---

pom.xml

Revert Bump htmlunit from 2.35.0 to 2.37.0 (as done in oxauth)

Revert Bump htmlunit from 2.35.0 to 2.37.0

---

oxd-server/src/main/java/org/gluu/oxd/server/op/RegisterSiteOperation.java

#510 - Save `client_id` and `client_secret` in oxd storage (in Rp table) when it is passed as paramater during client registration.
https://github.com/GluuFederation/oxd/issues/510

#510 - Save `client_id` and `client_secret` in oxd storage (in Rp table) when it is passed as paramater during client registration.

---

oxd-server/src/main/java/org/gluu/oxd/server/op/RegisterSiteOperation.java

#510 - Save `client_id` and `client_secret` in oxd storage (in Rp table) when it is passed as paramater during client registration
https://github.com/GluuFederation/oxd/issues/510

#510 - Save `client_id` and `client_secret` in oxd storage (in Rp table) when it is passed as paramater during client registration

---

oxd-common/src/main/java/org/gluu/oxd/common/ErrorResponseCode.java
oxd-server/src/main/java/org/gluu/oxd/server/Utils.java
oxd-server/src/main/java/org/gluu/oxd/server/op/RegisterSiteOperation.java

#526 - Minor: Show clear error message when get `redirect_uri` with fragment component during registration instead of generic `invalid_redirect_uri`
https://github.com/GluuFederation/oxd/issues/526

#526 - Minor: Show clear error message when get `redirect_uri` with fragment component during registration instead of generic `invalid_redirect_uri`

---

oxd-common/src/main/java/org/gluu/oxd/common/CoreUtils.java
oxd-server/src/main/java/org/gluu/oxd/server/OxdServerConfiguration.java
oxd-server/src/main/java/org/gluu/oxd/server/service/HttpService.java

#518  - For `private_key_jwt`, `tls_client_auth` , `self_signed_tls_client_auth` allow certificate-based client authentication.
https://github.com/GluuFederation/oxd/issues/518

#518 - For `private_key_jwt`, `tls_client_auth` , `self_signed_tls_client_auth` allow certificate-based client authentication.

---

oxd-common/src/main/java/org/gluu/oxd/common/ErrorResponseCode.java
oxd-server/src/main/java/org/gluu/oxd/server/op/Validator.java

https://github.com/GluuFederation/oxd/issues/536

#536 - If the ID Token contains multiple audiences, the Client shoud  verify that an azp Claim is present

---

oxd-common/src/main/java/org/gluu/oxd/common/ErrorResponseCode.java
oxd-server/src/main/java/org/gluu/oxd/server/op/Validator.java

#537 - The algorithm used to sign the `id_token` should match with `id_token_signed_response_alg` set during client registration.
https://github.com/GluuFederation/oxd/issues/537

#537 - The algorithm used to sign the `id_token` should match with `id_token_signed_response_alg` set during client registration.

---

oxd-server/src/main/java/org/gluu/oxd/server/OxdServerConfiguration.java
oxd-server/src/main/java/org/gluu/oxd/server/op/GetAuthorizationUrlOperation.java

#549 - Encode client_id in authorization_url (from `/get-authorization-url`)
https://github.com/GluuFederation/oxd/issues/549

#549 - Encode client_id in authorization_url (from `/get-authorization-url`)

---

oxd-common/src/main/java/org/gluu/oxd/common/params/RegisterSiteParams.java
oxd-common/src/main/java/org/gluu/oxd/common/params/UpdateSiteParams.java
oxd-gen-client/src/main/java/io/swagger/client/model/RegisterSiteParams.java
oxd-gen-client/src/test/java/io/swagger/client/api/RegisterSiteTest.java
oxd-server/src/main/java/org/gluu/oxd/server/mapper/RegisterRequestMapper.java
oxd-server/src/main/java/org/gluu/oxd/server/mapper/RegisterResponseMapper.java
oxd-server/src/main/java/org/gluu/oxd/server/op/RegisterSiteOperation.java
oxd-server/src/main/java/org/gluu/oxd/server/op/UpdateSiteOperation.java
oxd-server/src/main/java/org/gluu/oxd/server/service/Rp.java
oxd-server/src/main/resources/oxd-server.yml
oxd-server/src/main/resources/swagger.yaml
oxd-server/src/test/java/org/gluu/oxd/mock/AuthorizationCodeFlowTest.java
oxd-server/src/test/java/org/gluu/oxd/server/RegisterRequestMapperTest.java
oxd-server/src/test/java/org/gluu/oxd/server/RegisterSiteTest.java
oxd-server/src/test/java/org/gluu/oxd/server/RpGetRptTest.java
oxd-server/src/test/java/org/gluu/oxd/server/SetupClientTest.java
oxd-server/src/test/java/org/gluu/oxd/server/UpdateSiteTest.java
oxd-server/src/test/java/org/gluu/oxd/server/manual/NotAllowedTest.java

#553 - Change `client_frontchannel_logout_uri` from `List` to `string` type during client registration
https://github.com/GluuFederation/oxd/issues/553

#553 - Change `client_frontchannel_logout_uri` from `List` to `string` type during client registration

---

oxd-client/pom.xml
oxd-common/pom.xml
oxd-gen-client/pom.xml
oxd-server/pom.xml
pom.xml

#557 - Automation of swagger client generation in oxd
https://github.com/GluuFederation/oxd/issues/557
Changes done 
1. Generate swagger client using maven `swagger-codegen-maven-plugin` at starting in a temporary folder (`${oxd_home}/target/generated-sources`). 
2. Copy the generated sources from temporary folder to `oxd-gen-client` and delete the temporary folder.

#557 - Automation of swagger client generation in oxd

---

debian/oxd-server

`netstat` is not default in recent distros, `ss` is modern replacement and default. In this PR I also cleaned mixed whitespaces.

fix: use ss instead of netstat in oxd-server startup script
